<?php
session_start();
require_once '../config/database.php';

// --- Ensure collector is logged in ---
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'collector') {
    echo "Unauthorized access.";
    exit;
}

$payment_id = $_GET['id'] ?? null;
if (!$payment_id) {
    echo "Payment ID missing.";
    exit;
}

// Fetch payment with vendor info
$stmt = $pdo->prepare("
    SELECT p.*, v.stall_number, v.monthly_rent, s.section_name,
           u.first_name AS vendor_first, u.last_name AS vendor_last
    FROM payments p
    JOIN vendors v ON v.id = p.vendor_id
    JOIN users u ON u.id = v.user_id
    LEFT JOIN sections s ON s.id = v.section_id
    WHERE p.id = ? AND p.collector_id = ?
    LIMIT 1
");
$stmt->execute([$payment_id, $_SESSION['user_id']]);
$payment = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$payment) {
    echo "Payment not found or unauthorized.";
    exit;
}

// Calculations
$monthly_fee = $payment['monthly_rent'] ?? 0;
$discount_amount = $payment['discount'] ?? 0;
$penalty = $payment['penalty'] ?? 0;
$discount_percentage = $monthly_fee > 0 ? ($discount_amount / $monthly_fee) * 100 : 0;
$total_collected = ($monthly_fee - $discount_amount) + $penalty;

$collector_fullname = trim(($_SESSION['first_name'] ?? '') . ' ' . ($_SESSION['last_name'] ?? ''));
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Receipt #<?= htmlspecialchars($payment['id']) ?></title>
<?php include __DIR__ . '/includes/favicon.php'; ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body {
    font-family: 'Courier New', Courier, monospace;
    background:#f4f4f4;
    margin:0; padding:10px;
    display:flex; justify-content:center; align-items:flex-start;
}
.receipt-container {
    background:#fff;
    padding:15px;
    border:1px solid #ddd;
    box-shadow:0 0 10px rgba(0,0,0,0.1);
    width:320px;
}
.header { text-align:center; margin-bottom:5px; }
.header img { max-width:100px; margin-bottom:5px; }
.status { color:green; font-weight:bold; margin:3px 0; }
.table { width:100%; border-collapse:collapse; font-size:12px; }
.table td { padding:2px 0; }
.table td:last-child { text-align:right; }
.total-row { font-weight:bold; border-top:1px dashed #000; padding-top:2px; }
.footer { text-align:center; font-size:10px; margin-top:5px; }
.no-print { margin-top:10px; display:flex; justify-content:center; gap:10px; flex-wrap:wrap; }
button { padding:6px 12px; border:none; cursor:pointer; border-radius:4px; font-size:12px; }
.print-btn { background:#e67e22; color:white; }
.back-btn { background:#ecf0f1; border:1px solid #bdc3c7; }
@media print {
    body { background:none; padding:0; display:block; }
    .receipt-container { border:none; box-shadow:none; width:100%; max-width:none; }
    .no-print { display:none; }
}
</style>
</head>
<body>

<div class="receipt-container">
    <div class="header">
        <img src="../assets/images/logo.png" alt="RPMS Logo">
        <div class="status">Collection Successful!</div>
        <p>Receipt generated and ready to print</p>
    </div>

    <hr>

    <table class="table">
        <tr><td><strong>Receipt #:</strong></td><td><?= htmlspecialchars($payment['id']) ?></td></tr>
        <tr><td><strong>Date:</strong></td><td><?= date('m/d/Y', strtotime($payment['payment_date'])) ?></td></tr>
        <tr><td><strong>Time:</strong></td><td><?= date('h:i A', strtotime($payment['payment_date'])) ?></td></tr>
        <tr><td><strong>Collector:</strong></td><td><?= htmlspecialchars($collector_fullname) ?></td></tr>
    </table>

    <hr>

    <table class="table">
        <tr><td><strong>Stall #:</strong></td><td><?= htmlspecialchars($payment['stall_number']) ?></td></tr>
        <tr><td><strong>Vendor:</strong></td><td><?= htmlspecialchars($payment['vendor_first'].' '.$payment['vendor_last']) ?></td></tr>
        <tr><td>Monthly Fee:</td><td>₱<?= number_format($monthly_fee,2) ?></td></tr>
        <tr><td>Discount (<?= round($discount_percentage) ?>%):</td><td>- ₱<?= number_format($discount_amount,2) ?></td></tr>
        <tr><td>Penalty:</td><td>+ ₱<?= number_format($penalty,2) ?></td></tr>
        <tr class="total-row"><td>TOTAL COLLECTED:</td><td>₱<?= number_format($total_collected,2) ?></td></tr>
    </table>

    <hr>

    <div class="footer">
        <p>Thank you for your payment!</p>
        <p>Keep this receipt for your record</p>
        <p>Generated by: <?= htmlspecialchars($collector_fullname) ?></p>
        <p><strong>Collection Management System</strong></p>
    </div>


<div class="no-print">
    <button class="print-btn" onclick="window.print()">Print Receipt</button>
    <button class="back-btn" onclick="window.location.href='dashboard.php'">Back to Dashboard</button>
</div>
</div>

</body>
</html>
